name: my_tennis_team
description: A new Flutter project for My Tennis Team.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  google_sign_in: ^6.1.5
  http: ^1.1.0
  socket_io_client: ^2.0.3+1
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  go_router: ^12.0.0
  google_fonts: ^6.1.0
  fluttertoast: ^8.2.4
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
